---
# tasks file for all

  - name: deisable default route
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
    when: (ansible_hostname == "centralServer")

  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY=192.168.10.1
    when: (ansible_hostname == "centralServer")


