---
# tasks file for all

  - name: install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: install tcpdump && nano
    yum:
      state: present
      name:
        - tcpdump
        - nano

 


