---
# tasks file for all

  - name: http | install iptables
    yum:
      state: present
      name:
        - iptables
        - iptables-services
    when: (ansible_hostname == "inetRouter")
    
  - name: enable iptables service
    shell: systemctl enable iptables
    when: (ansible_hostname == "inetRouter")
  - name: start  iptables service
    shell: systemctl start iptables
    when: (ansible_hostname == "inetRouter")

  - name: copy iptables config
    template:
      src: ./files/iptables
      dest: /etc/sysconfig/iptables
    when: (ansible_hostname == "inetRouter")
 
  - name: restart  iptables service
    shell: systemctl restart iptables
    when: (ansible_hostname == "inetRouter")

  # - name: start and enable iptables service
  #   service:
  #     name: iptables
  #     state: restarted
  #   when: (ansible_hostname == "inetRouter")

  - name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present
    when: "'routers' in group_names"

