---
# tasks file for all

  - name: install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: install tcpdump && nano
    yum:
      state: present
      name:
        - tcpdump
        - nano

  - name: deisable default route
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
    when: (ansible_hostname == "centralServer")

  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY=192.168.10.1
    when: (ansible_hostname == "centralServer")


