---
# tasks file for routers

  - name: install iptables
    yum:
      name:
      - iptables
      - iptables-services
      state: present
      update_cache: true
  - name: copy iptables config
    template:
    src: ./files/iptables
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0600
  - name: start and enable iptables service
    service:
     name: iptables
     state: restarted
     enabled: true
    when: (ansible_hostname == "inetRouter")
  
  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present

  - name: deisable default route
    lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: DEFROUTE=no
    when: (ansible_hostname == "centralRouter") or
          (ansible_hostname == "centralServer")

  - name: add default gateway for centralRouter
    lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.255.1
    when: (ansible_hostname == "centralRouter")

  - name: add default gateway for centralServer
    lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.0.1
    when: (ansible_hostname == "centralServer")