---
  - name: install packages
    yum:
      state: present
      name:
        - tcpdump
        - nano
        - iptables
        - iptables-services
    when: (ansible_hostname == "inetRouter")
  - name: copy iptables config
    template:
      src: ./files/iptables
      dest: /etc/sysconfig/iptables
      owner: root
      group: root
      mode: 0600
    when: (ansible_hostname == "inetRouter")
    
  - name: start and enable iptables service
    service:
      name: iptables
      enabled: yes
    when: (ansible_hostname == "inetRouter")