---
  - name: install packages
    yum:
      state: present
      name:
        - tcpdump
        - nano
        - iptables
        - iptables-services
    when: (ansible_hostname == "inetRouter")

  - name: copy iptables config
    template:
      src: ./files/iptables
      dest: /etc/sysconfig/iptables
    when: (ansible_hostname == "inetRouter")
    
  - name: enable iptables service
    service:
      become: daemon_reload
      name: iptables
      state: started 
      enabled: yes
    when: (ansible_hostname == "inetRouter")
  
  - name: fix
    shell: echo "#" >> /etc/sysconfig/iptables
    when: (ansible_hostname == "inetRouter")

  - name: enable iptables service
    service:
      name: iptables
      state: restarted 
    when: (ansible_hostname == "inetRouter")

  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
