---
  - name: install packages
    yum:
      state: present
      name:
        - tcpdump
        - nano
        - iptables
        - iptables-services
    when: (ansible_hostname == "inetRouter")

  # - name: copy iptables config
  #   template:
  #     src: ./files/iptables
  #     dest: /etc/sysconfig/iptables
  #   when: (ansible_hostname == "inetRouter")

    
  - name: iptables-save
    shell: iptables-save >> /etc/sysconfig/iptables
    when: (ansible_hostname == "inetRouter")

  - name: enable iptables service
    service:
      name: iptables
      state: started 
      enabled: yes
    when: (ansible_hostname == "inetRouter")
  

  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present

  - name: deisable default route
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
    when: (ansible_hostname == "centralRouter")

  - name: add default gateway for centralRouter
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY=192.168.255.1
    when: (ansible_hostname == "centralRouter")

  # - name: copy route_inetRouter
  #   template:
  #     src: ./files/inetRouter
  #     dest: /etc/sysconfig/network-scripts/route-eth1
  #   when: (ansible_hostname == "inetRouter")

  # - name: copy route_centralServer
  #   template:
  #     src: ./files/centralServer
  #     dest: /etc/sysconfig/network-scripts/route-eth1
  #   when: (ansible_hostname == "centralServer")
 
  # - name: copy route_centralRouter5
  #   template:
  #     src: ./files/centralRouter5
  #     dest: /etc/sysconfig/network-scripts/route-eth5
  #   when: (ansible_hostname == "centralRouter")

  # - name: copy route_centralRouter6
  #   template:
  #     src: ./files/centralRouter6
  #     dest: /etc/sysconfig/network-scripts/route-eth6
  #   when: (ansible_hostname == "centralRouter")

  # - name: copy route_office2Router
  #   template:
  #     src: ./files/office2Router
  #     dest: /etc/sysconfig/network-scripts/route-eth1
  #   when: (ansible_hostname == "office2Router")

  # - name: copy route_office2Server
  #   template:
  #     src: ./files/office2Server
  #     dest: /etc/sysconfig/network-scripts/route-eth1
  #   when: (ansible_hostname == "office2Server")

  # - name: copy route_office1Router
  #   template:
  #     src: ./files/office1Router
  #     dest: /etc/sysconfig/network-scripts/route-eth1
  #   when: (ansible_hostname == "office1Router")

  # - name: copy route_office1Server
  #   template:
  #     src: ./files/office1Server
  #     dest: /etc/sysconfig/network-scripts/route-eth1
  #   when: (ansible_hostname == "office1Server")





