---
# tasks file for inet

  - name: http | install packages
    yum:
      state: present
      name:
        - iptables
        - iptables-services
        - tcpdump
        - nano

  - name: copy iptables config
    template:
      src: ./files/iptables
      dest: /etc/sysconfig/iptables

  - name: start and enable iptables service
    service:
      name: iptables
      state: restarted
