---
# tasks file for inet

  - name: install iptables
    yum:
      state: present
      name:
        - iptables
        - iptables-services
    

  - name: copy iptables config
    template:
      src: ./files/iptables
      dest: /etc/sysconfig/iptables
 
  - name: start and enable iptables service
    service:
      name: iptables
      state: restarted
      enabled: true
